apiVersion: apps/v1
kind: Deployment
metadata:
  name: rohit-deploy
  labels:
    app: insure-me
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insure-me
  template:
    metadata:
      labels:
        app: insure-me
    spec:
      containers:
      - name: rohit-container
        image: rohitpotdar/insure-me
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: insure-me-service
  labels:
    app: insure-me
spec:
  selector:
    app: insure-me
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30028

