apiVersion: apps/v1
kind: Deployment
metadata:
  name: rohit-deploy
  labels:
    app: rohit-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rohit-deploy
  template:
    metadata:
      labels:
        app: rohit-deploy
    spec:
      containers:
      - name: rohit-container
        image: rohitpotdar/insure-me
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rohit-np-service
  labels:
    app: rohit-deploy
spec:
  selector:
    app: rohit-deploy

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
